### ISSUE TITLE
Filtres

### ISSUE THREAD

**Issue by Mariehcqt** [Inheert/ThyroViz#12]
### Sur quels graphiques s'appliquent les filtres ? 

Ce que je comprends :  

- Le choix de la période de temps ne s’applique que sur le graphique de gauche 
- Les filtres du tableau s’appliquent partout 
- Sauf le filtre « only show observational articles” qui ne s’applique que sur le tableau 
Est-ce que c’est bien ça ?

**Comment by Inheert** [comment]
Maintenant sur tous
